In [1]:
import pandas as pd

In [2]:
import warnings

warnings.filterwarnings('ignore')

In [3]:
dataset_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n01PQ9pSmiRX6520flujwQ/survey-data.csv"

df = pd.read_csv(dataset_url)
print("Data successfully loaded!")

Data successfully loaded!


In [4]:
df.head()

ResponseId                      MainBranch                 Age  \
0           1  I am a developer by profession  Under 18 years old   
1           2  I am a developer by profession     35-44 years old   
2           3  I am a developer by profession     45-54 years old   
3           4           I am learning to code     18-24 years old   
4           5  I am a developer by profession     18-24 years old   

            Employment RemoteWork   Check  \
0  Employed, full-time     Remote  Apples   
1  Employed, full-time     Remote  Apples   
2  Employed, full-time     Remote  Apples   
3   Student, full-time        NaN  Apples   
4   Student, full-time        NaN  Apples   

                                    CodingActivities  \
0                                              Hobby   
1  Hobby;Contribute to open-source projects;Other...   
2  Hobby;Contribute to open-source projects;Other...   
3                                                NaN   
4                                                NaN   

                                             EdLevel  \
0                          Primary/elementary school   
1       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
2    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
3  Some college/university study without earning ...   
4  Secondary school (e.g. American high school, G...   

                                           LearnCode  \
0                             Books / Physical media   
1  Books / Physical media;Colleague;On the job tr...   
2  Books / Physical media;Colleague;On the job tr...   
3  Other online resources (e.g., videos, blogs, f...   
4  Other online resources (e.g., videos, blogs, f...   

                                     LearnCodeOnline  ... JobSatPoints_6  \
0                                                NaN  ...            NaN   
1  Technical documentation;Blogs;Books;Written Tu...  ...            0.0   
2  Technical documentation;Blogs;Books;Written Tu...  ...            NaN   
3  Stack Overflow;How-to videos;Interactive tutorial  ...            NaN   
4  Technical documentation;Blogs;Written Tutorial...  ...            NaN   

  JobSatPoints_7 JobSatPoints_8 JobSatPoints_9 JobSatPoints_10  \
0            NaN            NaN            NaN             NaN   
1            0.0            0.0            0.0             0.0   
2            NaN            NaN            NaN             NaN   
3            NaN            NaN            NaN             NaN   
4            NaN            NaN            NaN             NaN   

  JobSatPoints_11           SurveyLength SurveyEase ConvertedCompYearly JobSat  
0             NaN                    NaN        NaN                 NaN    NaN  
1             0.0                    NaN        NaN                 NaN    NaN  
2             NaN  Appropriate in length       Easy                 NaN    NaN  
3             NaN               Too long       Easy                 NaN    NaN  
4             NaN              Too short       Easy                 NaN    NaN  

[5 rows x 114 columns]

In [5]:
df_about_respondents = df


In [6]:
df_about_respondents.shape

(65437, 114)

In [7]:
df_about_respondents.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65437 entries, 0 to 65436
Columns: 114 entries, ResponseId to JobSat
dtypes: float64(13), int64(1), object(100)
memory usage: 56.9+ MB


In [8]:
df_about_respondents.MainBranch.unique()

array(['I am a developer by profession', 'I am learning to code',
       'I code primarily as a hobby',
       'I am not primarily a developer, but I write code sometimes as part of my work/studies',
       'I used to be a developer by profession, but no longer am'],
      dtype=object)

In [9]:
# Define a mapping for the 'MainBranch' column
MainBranch_Mapping = {
    'I am a developer by profession': 'developer by profession',
    'I am learning to code': 'learning to code',
    'I code primarily as a hobby': 'code as a hobby',
    'I am not primarily a developer, but I write code sometimes as part of my work/studies': 'code sometimes as part of work/studies',
    'I used to be a developer by profession, but no longer am': 'used to be a developer by profession'
}

df_about_respondents['MainBranch'] = df_about_respondents['MainBranch'].replace(MainBranch_Mapping)

print(df_about_respondents['MainBranch'].unique())

['developer by profession' 'learning to code' 'code as a hobby'
 'code sometimes as part of work/studies'
 'used to be a developer by profession']


In [10]:
df_about_respondents.Age.unique()

array(['Under 18 years old', '35-44 years old', '45-54 years old',
       '18-24 years old', '25-34 years old', '55-64 years old',
       'Prefer not to say', '65 years or older'], dtype=object)

In [11]:
# Define a mapping for the 'MainBranch' column
Age_Mapping = {
    'Under 18 years old': 'under 18',
    '18-24 years old': '18-24',
    '25-34 years old': '25-34',
    '35-44 years old': '35-44',
    '45-54 years old': '45-54',
    '55-64 years old': '55-64',
    '65 years or older': 'above 65',
    'Prefer not to say': 'non answer'
}

df_about_respondents['Age'] = df_about_respondents['Age'].replace(Age_Mapping)

print(df_about_respondents['Age'].unique())

['under 18' '35-44' '45-54' '18-24' '25-34' '55-64' 'non answer'
 'above 65']


In [12]:
df_about_respondents.Employment.unique()

array(['Employed, full-time', 'Student, full-time',
       'Student, full-time;Not employed, but looking for work',
       'Independent contractor, freelancer, or self-employed',
       'Not employed, and not looking for work',
       'Employed, full-time;Student, part-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed',
       'Employed, full-time;Student, full-time', 'Employed, part-time',
       'Student, full-time;Employed, part-time',
       'Student, part-time;Employed, part-time', 'I prefer not to say',
       'Not employed, but looking for work', 'Student, part-time',
       'Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Student, part-time',
       'Independent contractor, freelancer, or self-employed;Employed, part-time',
       'Independent contractor, freelancer, or self-employed;Student, par

In [13]:
def process_complex_column(df, column_name):
    """
    Process the  column to count occurrences and create binary columns for each unique value.

    Args:
        df (pd.DataFrame): The input dataframe.
        column_name (str): The name of the column to process.

    Returns:
        pd.DataFrame, pd.Series: Updated dataframe and counts of unique value.
    """
    # Split and count unique endorsements
    value_counts = df[column_name].str.split(';').explode().value_counts()

    # Generate binary columns for each unique endorsement
    unique_values = value_counts.index
    for col in unique_values:
        binary_column_name = f"{column_name}_{col.replace(' ', '').replace(':', '').replace(';', '').replace(',', '')}"
        df[binary_column_name] = df[column_name].str.contains(col, case=False, na=False).astype(int)

    df = df.drop(column_name, axis=1)

    return df, value_counts

In [14]:
df_about_respondents, Employment_Counts = process_complex_column(df_about_respondents, 'Employment')
print(Employment_Counts)

Employment
Employed, full-time                                     45162
Independent contractor, freelancer, or self-employed    10726
Student, full-time                                       8626
Employed, part-time                                      4145
Not employed, but looking for work                       3954
Student, part-time                                       2656
Not employed, and not looking for work                   1203
Retired                                                   681
I prefer not to say                                       546
Name: count, dtype: int64


In [15]:
df_about_respondents.RemoteWork.unique()

array(['Remote', nan, 'In-person', 'Hybrid (some remote, some in-person)'],
      dtype=object)

In [16]:
# Define a mapping for the 'MainBranch' column
RemoteWork_Mapping = {
    'Remote': 'remote',
    None: 'non answer',
    'In-person': 'in-person',
    'Hybrid (some remote, some in-person)': 'hybrid'
}

df_about_respondents['RemoteWork'] = df_about_respondents['RemoteWork'].replace(RemoteWork_Mapping)

print(df_about_respondents['RemoteWork'].unique())

['remote' 'non answer' 'in-person' 'hybrid']


In [17]:
df_about_respondents.Check.unique()

array(['Apples'], dtype=object)

In [18]:
df_about_respondents = df_about_respondents.drop('Check', axis=1)

In [19]:
df_about_respondents.CodingActivities.unique()

array(['Hobby',
       'Hobby;Contribute to open-source projects;Other (please specify):',
       nan, 'I don’t code outside of work', 'Bootstrapping a business',
       'Hobby;Contribute to open-source projects',
       'Hobby;School or academic work',
       'Hobby;Contribute to open-source projects;Professional development or self-paced learning from online courses',
       'Hobby;Professional development or self-paced learning from online courses',
       'Contribute to open-source projects;Other (please specify):',
       'Contribute to open-source projects',
       'Hobby;Freelance/contract work',
       'Professional development or self-paced learning from online courses',
       'Hobby;Other (please specify):;Bootstrapping a business',
       'Freelance/contract work',
       'Contribute to open-source projects;Bootstrapping a business;School or academic work',
       'Contribute to open-source projects;Bootstrapping a business;Freelance/contract work',
       'Hobby;Contribute

In [20]:
df_about_respondents, CodingActivities_Counts = process_complex_column(df_about_respondents, 'CodingActivities')
print(CodingActivities_Counts)

CodingActivities
Hobby                                                                  37226
Professional development or self-paced learning from online courses    21513
Contribute to open-source projects                                     13717
Freelance/contract work                                                10513
Bootstrapping a business                                                8194
School or academic work                                                 7069
I don’t code outside of work                                            6508
Other (please specify):                                                 1098
Name: count, dtype: int64


In [21]:
df_about_respondents.EdLevel.unique()

array(['Primary/elementary school',
       'Bachelor’s degree (B.A., B.S., B.Eng., etc.)',
       'Master’s degree (M.A., M.S., M.Eng., MBA, etc.)',
       'Some college/university study without earning a degree',
       'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)',
       'Professional degree (JD, MD, Ph.D, Ed.D, etc.)',
       'Associate degree (A.A., A.S., etc.)', 'Something else', nan],
      dtype=object)

In [22]:
EdLevel_Mapping = {
    'Primary/elementary school': 'Primary School',
    'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)': 'Secondary school',
    'Associate degree (A.A., A.S., etc.)': 'Associate degree',
    'Bachelor’s degree (B.A., B.S., B.Eng., etc.)': 'Bachelor’s degree',
    'Master’s degree (M.A., M.S., M.Eng., MBA, etc.)': 'Master’s degree',
    'Professional degree (JD, MD, Ph.D, Ed.D, etc.)': 'Professional degree',
    'Some college/university study without earning a degree': 'College without a degree',
    'Something else': 'other',
    None: 'non answer'
}

df_about_respondents['EdLevel'] = df_about_respondents['EdLevel'].replace(EdLevel_Mapping)

print(df_about_respondents['EdLevel'].unique())

['Primary School' 'Bachelor’s degree' 'Master’s degree'
 'College without a degree' 'Secondary school' 'Professional degree'
 'Associate degree' 'other' 'non answer']


In [23]:
df_about_respondents.LearnCode.unique()

array(['Books / Physical media',
       'Books / Physical media;Colleague;On the job training;Other online resources (e.g., videos, blogs, forum, online community)',
       'Books / Physical media;Colleague;On the job training;Other online resources (e.g., videos, blogs, forum, online community);School (i.e., University, College, etc)',
       'Other online resources (e.g., videos, blogs, forum, online community);School (i.e., University, College, etc);Online Courses or Certification',
       'Other online resources (e.g., videos, blogs, forum, online community)',
       'School (i.e., University, College, etc);Online Courses or Certification',
       'Other online resources (e.g., videos, blogs, forum, online community);Online Courses or Certification;Coding Bootcamp',
       'Books / Physical media;Other online resources (e.g., videos, blogs, forum, online community);Online Courses or Certification',
       'On the job training;Other online resources (e.g., videos, blogs, forum, onli

In [24]:
df_about_respondents = df_about_respondents.drop('LearnCode', axis=1)

In [25]:
df_about_respondents.LearnCodeOnline.unique()

array([nan,
       'Technical documentation;Blogs;Books;Written Tutorials;Stack Overflow',
       'Technical documentation;Blogs;Books;Written Tutorials;Stack Overflow;Coding sessions (live or recorded);Social Media',
       ...,
       'Technical documentation;Blogs;Written Tutorials;Stack Overflow;Coding sessions (live or recorded);How-to videos;Video-based Online Courses;Written-based Online Courses;Programming Games',
       'Technical documentation;Blogs;Books;Written Tutorials;Coding sessions (live or recorded);How-to videos;Written-based Online Courses;Online challenges (e.g., daily or weekly coding challenges)',
       'Blogs;Stack Overflow;Social Media;Video-based Online Courses;Written-based Online Courses;AI'],
      dtype=object)

In [26]:
df_about_respondents = df_about_respondents.drop('LearnCodeOnline', axis=1)

In [27]:
df_about_respondents.TechDoc.unique()

array([nan,
       'API document(s) and/or SDK document(s);User guides or README files found in the source repository;First-party knowledge base;Traditional public search engine',
       'API document(s) and/or SDK document(s);User guides or README files found in the source repository;Traditional public search engine',
       'First-party knowledge base',
       'Traditional public search engine;AI-powered search/dev tool (free)',
       'API document(s) and/or SDK document(s);User guides or README files found in the source repository;Traditional public search engine;AI-powered search/dev tool (free)',
       'API document(s) and/or SDK document(s)',
       'API document(s) and/or SDK document(s);Traditional public search engine',
       'API document(s) and/or SDK document(s);Traditional public search engine;AI-powered search/dev tool (free);AI-powered search/dev tool (paid)',
       'API document(s) and/or SDK document(s);User guides or README files found in the source repository;Fir

In [28]:
df_about_respondents = df_about_respondents.drop('TechDoc', axis=1)

In [29]:
df_about_respondents.YearsCode.unique()

array([nan, '20', '37', '4', '9', '10', '7', '1', '15', '30', '31', '6',
       '12', '22', '5', '36', '25', '44', '24', '18', '3', '8',
       'More than 50 years', '11', '29', '40', '39', '2', '42', '34',
       '19', '35', '16', '33', '13', '23', '14', '28', '17', '21', '43',
       '46', '26', '32', '41', '45', '27', '38', '50', '48', '47',
       'Less than 1 year', '49'], dtype=object)

In [30]:
YearsCode_Mapping = {
    'Less than 1 year': '0.5',
    'More than 50 years': '51'
}

df_about_respondents['YearsCode'] = df_about_respondents['YearsCode'].replace(YearsCode_Mapping)
df_about_respondents['YearsCode'] = df_about_respondents['YearsCode'].astype(float)
print(df_about_respondents['YearsCode'].unique())

[ nan 20.  37.   4.   9.  10.   7.   1.  15.  30.  31.   6.  12.  22.
  5.  36.  25.  44.  24.  18.   3.   8.  51.  11.  29.  40.  39.   2.
 42.  34.  19.  35.  16.  33.  13.  23.  14.  28.  17.  21.  43.  46.
 26.  32.  41.  45.  27.  38.  50.  48.  47.   0.5 49. ]


In [31]:
df_about_respondents['YearsCode'].isnull().sum()


np.int64(5568)

In [32]:
df_about_respondents.YearsCodePro.unique()

array([nan, '17', '27', '7', '11', '25', '12', '10', '3',
       'Less than 1 year', '18', '37', '15', '20', '6', '2', '16', '8',
       '14', '4', '45', '1', '24', '29', '5', '30', '26', '9', '33', '13',
       '35', '23', '22', '31', '19', '21', '28', '34', '32', '40', '50',
       '39', '44', '42', '41', '36', '38', 'More than 50 years', '43',
       '47', '48', '46', '49'], dtype=object)

In [33]:
YearsCodePro_Mapping = {
    'Less than 1 year': '0.5',
    'More than 50 years': '51'
}

df_about_respondents['YearsCodePro'] = df_about_respondents['YearsCodePro'].replace(YearsCodePro_Mapping)
df_about_respondents['YearsCodePro'] = df_about_respondents['YearsCodePro'].astype(float)
print(df_about_respondents['YearsCodePro'].unique())

[ nan 17.  27.   7.  11.  25.  12.  10.   3.   0.5 18.  37.  15.  20.
  6.   2.  16.   8.  14.   4.  45.   1.  24.  29.   5.  30.  26.   9.
 33.  13.  35.  23.  22.  31.  19.  21.  28.  34.  32.  40.  50.  39.
 44.  42.  41.  36.  38.  51.  43.  47.  48.  46.  49. ]


In [34]:
df_about_respondents['YearsCodePro'].isnull().sum()


np.int64(13827)

In [35]:
df_about_respondents.DevType.unique()

array([nan, 'Developer, full-stack', 'Developer Experience', 'Student',
       'Academic researcher', 'Project manager', 'Developer Advocate',
       'Developer, back-end', 'Other (please specify):',
       'Developer, front-end', 'Database administrator',
       'Developer, desktop or enterprise applications',
       'Cloud infrastructure engineer',
       'Data scientist or machine learning specialist',
       'Research & Development role',
       'Developer, embedded applications or devices',
       'System administrator', 'DevOps specialist', 'Engineering manager',
       'Designer', 'Security professional',
       'Senior Executive (C-Suite, VP, etc.)', 'Developer, mobile',
       'Developer, game or graphics', 'Data or business analyst',
       'Educator', 'Developer, QA or test', 'Product manager',
       'Developer, AI', 'Scientist', 'Engineer, site reliability',
       'Blockchain', 'Marketing or sales professional',
       'Hardware Engineer', 'Data engineer'], dtype=object)

In [36]:
df_about_respondents['DevType'].fillna('no answer', inplace=True)


In [37]:
df_about_respondents.OrgSize.unique()

array([nan, '100 to 499 employees', '2 to 9 employees',
       'Just me - I am a freelancer, sole proprietor, etc.',
       '10 to 19 employees', '20 to 99 employees',
       '5,000 to 9,999 employees', '1,000 to 4,999 employees',
       'I don’t know', '10,000 or more employees', '500 to 999 employees'],
      dtype=object)

In [38]:
OrgSize_Mapping = {
    'Just me - I am a freelancer, sole proprietor, etc.': 'Just me',
    '2 to 9 employees': '2 - 9',
    '10 to 19 employees': '10 - 19',
    '20 to 99 employees': '20 - 99',
    '100 to 499 employees': '100 - 499',
    '500 to 999 employees': '500 - 999',
    '1,000 to 4,999 employees': '1,000 - 4,999',
    '5,000 to 9,999 employees': '5,000 - 9,999',
    '10,000 or more employees': '> 10,000',
    'I don’t know': 'I do not know',
    None: 'no answer'
}

df_about_respondents['OrgSize'] = df_about_respondents['OrgSize'].replace(OrgSize_Mapping)
print(df_about_respondents['OrgSize'].unique())

['no answer' '100 - 499' '2 - 9' 'Just me' '10 - 19' '20 - 99'
 '5,000 - 9,999' '1,000 - 4,999' 'I do not know' '> 10,000' '500 - 999']


In [39]:
df_about_respondents.PurchaseInfluence.unique()

array([nan, 'I have some influence', 'I have little or no influence',
       'I have a great deal of influence'], dtype=object)

In [40]:
PurchaseInfluence_Mapping = {
    'I have little or no influence': 'no/little',
    'I have some influence': 'some',
    'I have a great deal of influence': 'great',
    None: 'no answer'
}

df_about_respondents['PurchaseInfluence'] = df_about_respondents['PurchaseInfluence'].replace(PurchaseInfluence_Mapping)
print(df_about_respondents['PurchaseInfluence'].unique())

['no answer' 'some' 'no/little' 'great']


In [41]:
df_about_respondents.BuyNewTool.unique()

array([nan,
       'Start a free trial;Ask developers I know/work with;Ask a generative AI tool;Visit developer communities like Stack Overflow;Read ratings or reviews on third party sites like G2 Crowd',
       'Start a free trial',
       'Start a free trial;Ask developers I know/work with;Visit developer communities like Stack Overflow',
       'Start a free trial;Ask developers I know/work with;Visit developer communities like Stack Overflow;Read ratings or reviews on third party sites like G2 Crowd;Research companies that have advertised on sites I visit;Research companies that have emailed me',
       'Ask developers I know/work with;Research companies that have emailed me',
       'Ask developers I know/work with;Read ratings or reviews on third party sites like G2 Crowd',
       'Ask developers I know/work with',
       'Start a free trial;Research companies that have advertised on sites I visit;Research companies that have emailed me',
       'Start a free trial;Ask developers

In [42]:
df_about_respondents = df_about_respondents.drop('BuyNewTool', axis=1)

In [43]:
df_about_respondents.BuildvsBuy.unique()

array([nan,
       'Is ready-to-go but also customizable for growth and targeted use cases',
       'Is set up to be customized and needs to be engineered into a usable product',
       'Out-of-the-box is ready to go with little need for customization'],
      dtype=object)

In [44]:
df_about_respondents['BuildvsBuy'].fillna('no answer', inplace=True)


In [45]:
df_about_respondents.TechEndorse.unique()

array([nan,
       'APIs;Customization;Integrated developer community;Quality support system;AI tool integration;Reputation for quality and excellence;Frequent updates to features',
       'APIs;Integrated developer community;Reputation for quality and excellence;Connected to an open source project',
       'APIs;Customization;Integrated developer community;Quality support system;Reputation for quality and excellence;Connected to an open source project',
       'APIs;Reputation for quality and excellence;Frequent updates to features',
       'APIs;Connected to an open source project',
       'APIs;Reputation for quality and excellence;Connected to an open source project',
       'Integrated developer community;Reputation for quality and excellence;Frequent updates to features',
       'Customization',
       'APIs;Customization;Reputation for quality and excellence;Frequent updates to features',
       'APIs;Customization;Integrated developer community;Quality support system;Reputation

In [46]:
df_about_respondents = df_about_respondents.drop('TechEndorse', axis=1)

In [47]:
df_about_respondents.Country.unique()

array(['United States of America',
       'United Kingdom of Great Britain and Northern Ireland', 'Canada',
       'Norway', 'Uzbekistan', 'Serbia', 'Poland', 'Philippines',
       'Bulgaria', 'Switzerland', 'India', 'Germany', 'Ireland', 'Italy',
       'Ukraine', 'Australia', 'Brazil', 'Japan', 'Austria',
       'Iran, Islamic Republic of...', 'France', 'Saudi Arabia',
       'Romania', 'Turkey', 'Nepal', 'Algeria', 'Sweden', 'Netherlands',
       'Croatia', 'Pakistan', 'Czech Republic',
       'Republic of North Macedonia', 'Finland', 'Slovakia',
       'Russian Federation', 'Greece', 'Israel', 'Belgium', 'Mexico',
       'United Republic of Tanzania', 'Hungary', 'Argentina', 'Portugal',
       'Sri Lanka', 'Latvia', 'China', 'Singapore', 'Lebanon', 'Spain',
       'South Africa', 'Lithuania', 'Viet Nam', 'Dominican Republic',
       'Indonesia', 'Kosovo', 'Morocco', 'Taiwan', 'Georgia',
       'San Marino', 'Tunisia', 'Bangladesh', 'Nigeria', 'Liechtenstein',
       'Denmark', 'Ecu

In [48]:
Country_Mapping = {
    'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom',
    'Iran, Islamic Republic of...': 'Islamic Republic of Iran',
    'Venezuela, Bolivarian Republic of...': 'Bolivarian Republic of Venezuela',
    'Micronesia, Federated States of...': 'Federated States of Micronesia',
    'Congo, Republic of the...': 'Republic of the Congo',
    None: 'no answer'
}

df_about_respondents['Country'] = df_about_respondents['Country'].replace(Country_Mapping)
print(df_about_respondents['Country'].unique())

['United States of America' 'United Kingdom' 'Canada' 'Norway'
 'Uzbekistan' 'Serbia' 'Poland' 'Philippines' 'Bulgaria' 'Switzerland'
 'India' 'Germany' 'Ireland' 'Italy' 'Ukraine' 'Australia' 'Brazil'
 'Japan' 'Austria' 'Islamic Republic of Iran' 'France' 'Saudi Arabia'
 'Romania' 'Turkey' 'Nepal' 'Algeria' 'Sweden' 'Netherlands' 'Croatia'
 'Pakistan' 'Czech Republic' 'Republic of North Macedonia' 'Finland'
 'Slovakia' 'Russian Federation' 'Greece' 'Israel' 'Belgium' 'Mexico'
 'United Republic of Tanzania' 'Hungary' 'Argentina' 'Portugal'
 'Sri Lanka' 'Latvia' 'China' 'Singapore' 'Lebanon' 'Spain' 'South Africa'
 'Lithuania' 'Viet Nam' 'Dominican Republic' 'Indonesia' 'Kosovo'
 'Morocco' 'Taiwan' 'Georgia' 'San Marino' 'Tunisia' 'Bangladesh'
 'Nigeria' 'Liechtenstein' 'Denmark' 'Ecuador' 'Malaysia' 'Albania'
 'Azerbaijan' 'Chile' 'Ghana' 'Peru' 'Bolivia' 'Egypt' 'Luxembourg'
 'Montenegro' 'Cyprus' 'Paraguay' 'Kazakhstan' 'Slovenia' 'Jordan'
 'Bolivarian Republic of Venezuela' 'Costa R

In [49]:
df_about_respondents.Currency.unique()

array([nan, 'PKR\tPakistani rupee', 'EUR European Euro',
       'USD\tUnited States dollar', 'BRL\tBrazilian real',
       'GBP\tPound sterling', 'RON\tRomanian leu', 'INR\tIndian rupee',
       'CHF\tSwiss franc', 'TRY\tTurkish lira', 'RUB\tRussian ruble',
       'ZAR\tSouth African rand', 'CZK\tCzech koruna',
       'CAD\tCanadian dollar', 'IRR\tIranian rial', 'MXN\tMexican peso',
       'UAH\tUkrainian hryvnia', 'DOP\tDominican peso',
       'KMF\tComorian franc', 'RSD\tSerbian dinar', 'PEN\tPeruvian sol',
       'MAD\tMoroccan dirham', 'GEL\tGeorgian lari', 'PLN\tPolish zloty',
       'SAR\tSaudi Arabian riyal', 'SEK\tSwedish krona',
       'BGN\tBulgarian lev', 'KZT\tKazakhstani tenge',
       'SGD\tSingapore dollar', 'JOD\tJordanian dinar',
       'JPY\tJapanese yen', 'NOK\tNorwegian krone',
       'ILS\tIsraeli new shekel', 'DKK\tDanish krone', 'THB\tThai baht',
       'RWF\tRwandan franc', 'HUF\tHungarian forint',
       'BDT\tBangladeshi taka', 'IDR\tIndonesian rupiah',
      

In [50]:
df_about_respondents[['CurrencyCode', 'CurrencyName']] = df_about_respondents['Currency'].str.extract(r'(\w+)[\t ]+(.*)')

df_about_respondents['CurrencyCode'].fillna('no answer', inplace=True)
df_about_respondents['CurrencyName'].fillna('no answer', inplace=True)

In [51]:
df_about_respondents = df_about_respondents.drop('Currency', axis=1)

In [52]:
df_about_respondents.CompTotal.unique()

array([     nan, 2040000.,   28000., ...,  254600.,  247433.,   77700.])

In [53]:
df_about_respondents.CompTotal.value_counts()

CompTotal
100000.0     939
60000.0      839
120000.0     793
80000.0      728
50000.0      705
            ... 
83363.0        1
4848000.0      1
42720.0        1
6770000.0      1
578000.0       1
Name: count, Length: 3337, dtype: int64

In [54]:
df_about_respondents.LanguageHaveWorkedWith.unique()

array([nan,
       'Bash/Shell (all shells);Go;HTML/CSS;Java;JavaScript;Python;TypeScript',
       'C#', ...,
       'Bash/Shell (all shells);C;C#;C++;Delphi;Groovy;HTML/CSS;Java;JavaScript;Objective-C;PowerShell;Python;SQL;Swift;TypeScript',
       'C;C++;Go;Lua;Objective-C;Python;Rust;SQL',
       'C;HTML/CSS;Java;JavaScript;PHP;Python;TypeScript'], dtype=object)

In [55]:
df_about_respondents, LanguageHaveWorkedWith_Counts = process_complex_column(df_about_respondents, 'LanguageHaveWorkedWith')
print(LanguageHaveWorkedWith_Counts)

LanguageHaveWorkedWith
JavaScript                 37492
HTML/CSS                   31816
Python                     30719
SQL                        30682
TypeScript                 23150
Bash/Shell (all shells)    20412
Java                       18239
C#                         16318
C++                        13827
C                          12184
PHP                        10951
PowerShell                  8328
Go                          8103
Rust                        7559
Kotlin                      5665
Lua                         3728
Dart                        3594
Assembly                    3233
Ruby                        3147
Swift                       2829
R                           2595
Visual Basic (.Net)         2499
MATLAB                      2378
VBA                         2248
Groovy                      2004
Scala                       1547
Perl                        1482
GDScript                    1402
Objective-C                 1283
Elixir              

In [56]:
df_about_respondents.LanguageWantToWorkWith.unique()

array([nan,
       'Bash/Shell (all shells);Go;HTML/CSS;Java;JavaScript;Kotlin;Python;TypeScript',
       'C#', ...,
       'Bash/Shell (all shells);C;C++;Elixir;Erlang;Go;HTML/CSS;Java;JavaScript;Kotlin;Lua;PowerShell;Python;Rust;Solidity;SQL;TypeScript;VBA;Visual Basic (.Net);Zig',
       'Bash/Shell (all shells);C;C++;Python;Ruby;SQL',
       'Bash/Shell (all shells);C#;Go;HTML/CSS;Java;JavaScript;Kotlin;Objective-C;Python;Rust;SQL;Swift;TypeScript'],
      dtype=object)

In [57]:
df_about_respondents, LanguageWantToWorkWith_Counts = process_complex_column(df_about_respondents, 'LanguageWantToWorkWith')
print(LanguageWantToWorkWith_Counts)

LanguageWantToWorkWith
Python                     25047
JavaScript                 23774
SQL                        22400
HTML/CSS                   20721
TypeScript                 20239
Rust                       17232
Go                         13837
Bash/Shell (all shells)    13744
C#                         12921
C++                        10873
Java                       10668
C                           8275
Kotlin                      7379
PHP                         5745
PowerShell                  4287
Swift                       3877
Dart                        3709
Zig                         3688
Lua                         3322
Assembly                    3007
Elixir                      2895
Ruby                        2774
Haskell                     2221
R                           2177
Scala                       1790
GDScript                    1667
Clojure                     1331
F#                          1272
Julia                       1263
Lisp                

In [58]:
df_about_respondents.LanguageAdmired.unique()

array([nan,
       'Bash/Shell (all shells);Go;HTML/CSS;Java;JavaScript;Python;TypeScript',
       'C#', ..., 'Elixir;Lua;Python;Ruby;SQL',
       'Bash/Shell (all shells);C;C++;HTML/CSS;Java;JavaScript;PowerShell;Rust;Solidity;SQL;TypeScript;VBA;Visual Basic (.Net)',
       'Bash/Shell (all shells);C#;HTML/CSS;Java;JavaScript;Objective-C;Python;SQL;Swift;TypeScript'],
      dtype=object)

In [59]:
df_about_respondents = df_about_respondents.drop('LanguageAdmired', axis=1)

In [60]:
df_about_respondents.DatabaseHaveWorkedWith.unique()

array([nan, 'Dynamodb;MongoDB;PostgreSQL', 'Firebase Realtime Database',
       ..., 'MySQL;Presto;Redis;TiDB',
       'Dynamodb;Elasticsearch;IBM DB2;MariaDB;MySQL;PostgreSQL',
       'Couch DB;H2;Microsoft SQL Server;MySQL;Oracle;PostgreSQL;SQLite'],
      dtype=object)

In [61]:
df_about_respondents, DatabaseHaveWorkedWith_Counts = process_complex_column(df_about_respondents, 'DatabaseHaveWorkedWith')
print(DatabaseHaveWorkedWith_Counts)

DatabaseHaveWorkedWith
PostgreSQL                    25536
MySQL                         21099
SQLite                        17365
Microsoft SQL Server          13275
MongoDB                       13007
Redis                         10463
MariaDB                        8991
Elasticsearch                  6533
Oracle                         5273
Dynamodb                       4138
Firebase Realtime Database     3018
Cloud Firestore                2842
BigQuery                       2531
Microsoft Access               2193
Supabase                       2078
H2                             2006
Cosmos DB                      1746
Snowflake                      1364
InfluxDB                       1338
Cassandra                      1268
Databricks SQL                 1003
Neo4J                           998
IBM DB2                         914
Clickhouse                      890
Solr                            766
DuckDB                          710
Firebird                        563
Couch

In [62]:
df_about_respondents.DatabaseWantToWorkWith.unique()

array([nan, 'PostgreSQL', 'Firebase Realtime Database', ...,
       'Cassandra;Firebase Realtime Database;MariaDB;Microsoft Access;MongoDB;MySQL;PostgreSQL;Redis',
       'MySQL;Presto;TiDB',
       'BigQuery;Cassandra;Databricks SQL;DuckDB;Elasticsearch;Firebase Realtime Database;Microsoft SQL Server;MongoDB;MySQL;PostgreSQL;Redis;Snowflake;SQLite;Supabase'],
      dtype=object)

In [63]:
df_about_respondents, DatabaseWantToWorkWith_Counts = process_complex_column(df_about_respondents, 'DatabaseWantToWorkWith')
print(DatabaseWantToWorkWith_Counts)

DatabaseWantToWorkWith
PostgreSQL                    24005
SQLite                        13489
MySQL                         12269
MongoDB                       10982
Redis                         10847
Microsoft SQL Server           7905
Elasticsearch                  6246
MariaDB                        5947
Dynamodb                       3503
Supabase                       2930
Oracle                         2636
BigQuery                       2554
Firebase Realtime Database     2536
Cassandra                      2399
Cloud Firestore                2119
Snowflake                      1784
Cosmos DB                      1764
Neo4J                          1570
DuckDB                         1468
Clickhouse                     1328
Databricks SQL                 1218
Cockroachdb                    1157
InfluxDB                       1090
H2                             1040
Microsoft Access                662
Couch DB                        620
Solr                            558
Fireb

In [64]:
df_about_respondents.DatabaseAdmired.unique()

array([nan, 'PostgreSQL', 'Firebase Realtime Database', ...,
       'Cassandra;Cloud Firestore;Cosmos DB;Microsoft SQL Server;MongoDB;MySQL;PostgreSQL;Redis;SQLite;Supabase',
       'MariaDB;Microsoft Access;MongoDB;MySQL;PostgreSQL;Redis',
       'MySQL;Presto;TiDB'], dtype=object)

In [65]:
df_about_respondents = df_about_respondents.drop('DatabaseAdmired', axis=1)

In [66]:
df_about_respondents.PlatformHaveWorkedWith.unique()

array([nan, 'Amazon Web Services (AWS);Heroku;Netlify', 'Google Cloud',
       ...,
       'Amazon Web Services (AWS);Cloudflare;Digital Ocean;Google Cloud;Microsoft Azure;Netlify;PythonAnywhere;Render',
       'Alibaba Cloud;Amazon Web Services (AWS);Colocation;Databricks;Firebase;Fly.io;Google Cloud;Heroku;Managed Hosting;Microsoft Azure;Netlify;OpenStack;PythonAnywhere;Vercel;VMware',
       'Amazon Web Services (AWS);Cloudflare;Firebase;Linode, now Akamai;Vercel'],
      dtype=object)

In [67]:
df_about_respondents, PlatformHaveWorkedWith_Counts = process_complex_column(df_about_respondents, 'PlatformHaveWorkedWith')
print(PlatformHaveWorkedWith_Counts)

PlatformHaveWorkedWith
Amazon Web Services (AWS)            22191
Microsoft Azure                      12850
Google Cloud                         11605
Cloudflare                            6974
Firebase                              6443
Vercel                                5491
Digital Ocean                         5409
Heroku                                3798
Netlify                               3238
VMware                                3043
Hetzner                               2301
Supabase                              1767
Linode, now Akamai                    1425
OVH                                   1397
Managed Hosting                       1386
Oracle Cloud Infrastructure (OCI)     1332
Render                                1305
Fly.io                                1189
OpenShift                             1120
Databricks                             918
PythonAnywhere                         892
Vultr                                  798
OpenStack                      

In [68]:
df_about_respondents.PlatformWantToWorkWith.unique()

array([nan, 'Amazon Web Services (AWS);Heroku;Netlify', 'Google Cloud',
       ...,
       'Amazon Web Services (AWS);Cloudflare;Firebase;Google Cloud;Heroku;Microsoft Azure;OVH;Vercel',
       'Amazon Web Services (AWS);Google Cloud;Heroku;Linode, now Akamai;Vercel',
       'PythonAnywhere;Render;Vercel'], dtype=object)

In [69]:
df_about_respondents = df_about_respondents.drop('PlatformWantToWorkWith', axis=1)

In [70]:
df_about_respondents.PlatformAdmired.unique()

array([nan, 'Amazon Web Services (AWS);Heroku;Netlify', 'Google Cloud',
       ..., 'Firebase;Microsoft Azure;Netlify;Vercel',
       'Amazon Web Services (AWS);Google Cloud;Heroku;Linode, now Akamai;Vercel',
       'PythonAnywhere;Render;Vercel'], dtype=object)

In [71]:
df_about_respondents = df_about_respondents.drop('PlatformAdmired', axis=1)

In [72]:
df_about_respondents = df_about_respondents.drop('WebframeHaveWorkedWith', axis=1)
df_about_respondents = df_about_respondents.drop('WebframeWantToWorkWith', axis=1)
df_about_respondents = df_about_respondents.drop('WebframeAdmired', axis=1)
df_about_respondents = df_about_respondents.drop('EmbeddedHaveWorkedWith', axis=1)
df_about_respondents = df_about_respondents.drop('EmbeddedWantToWorkWith', axis=1)
df_about_respondents = df_about_respondents.drop('EmbeddedAdmired', axis=1)
df_about_respondents = df_about_respondents.drop('MiscTechHaveWorkedWith', axis=1)
df_about_respondents = df_about_respondents.drop('MiscTechWantToWorkWith', axis=1)
df_about_respondents = df_about_respondents.drop('MiscTechAdmired', axis=1)
df_about_respondents = df_about_respondents.drop('ToolsTechHaveWorkedWith', axis=1)
df_about_respondents = df_about_respondents.drop('ToolsTechWantToWorkWith', axis=1)
df_about_respondents = df_about_respondents.drop('ToolsTechAdmired', axis=1)

df_about_respondents = df_about_respondents.drop('NEWCollabToolsHaveWorkedWith', axis=1)
df_about_respondents = df_about_respondents.drop('NEWCollabToolsWantToWorkWith', axis=1)
df_about_respondents = df_about_respondents.drop('NEWCollabToolsAdmired', axis=1)
df_about_respondents = df_about_respondents.drop('OpSysPersonal use', axis=1)
df_about_respondents = df_about_respondents.drop('OpSysProfessional use', axis=1)
df_about_respondents = df_about_respondents.drop('OfficeStackAsyncHaveWorkedWith', axis=1)
df_about_respondents = df_about_respondents.drop('OfficeStackAsyncWantToWorkWith', axis=1)
df_about_respondents = df_about_respondents.drop('OfficeStackAsyncAdmired', axis=1)

df_about_respondents = df_about_respondents.drop('OfficeStackSyncHaveWorkedWith', axis=1)
df_about_respondents = df_about_respondents.drop('OfficeStackSyncWantToWorkWith', axis=1)
df_about_respondents = df_about_respondents.drop('OfficeStackSyncAdmired', axis=1)
df_about_respondents = df_about_respondents.drop('AISearchDevHaveWorkedWith', axis=1)
df_about_respondents = df_about_respondents.drop('AISearchDevWantToWorkWith', axis=1)
df_about_respondents = df_about_respondents.drop('AISearchDevAdmired', axis=1)

In [73]:
df_about_respondents = df_about_respondents.drop('SOVisitFreq', axis=1)
df_about_respondents = df_about_respondents.drop('SOAccount', axis=1)
df_about_respondents = df_about_respondents.drop('SOPartFreq', axis=1)
df_about_respondents = df_about_respondents.drop('SOHow', axis=1)
df_about_respondents = df_about_respondents.drop('SOComm', axis=1)

In [74]:
df_about_respondents = df_about_respondents.drop('AISent', axis=1)
df_about_respondents = df_about_respondents.drop('AIBen', axis=1)
df_about_respondents = df_about_respondents.drop('AIAcc', axis=1)
df_about_respondents = df_about_respondents.drop('AIComplex', axis=1)
df_about_respondents = df_about_respondents.drop('AIToolCurrently Using', axis=1)
df_about_respondents = df_about_respondents.drop('AIToolInterested in Using', axis=1)
df_about_respondents = df_about_respondents.drop('AIToolNot interested in Using', axis=1)
df_about_respondents = df_about_respondents.drop('AINextMuch more integrated', axis=1)
df_about_respondents = df_about_respondents.drop('AINextNo change', axis=1)
df_about_respondents = df_about_respondents.drop('AINextMore integrated', axis=1)

df_about_respondents = df_about_respondents.drop('AINextLess integrated', axis=1)
df_about_respondents = df_about_respondents.drop('AINextMuch less integrated', axis=1)
df_about_respondents = df_about_respondents.drop('AIThreat', axis=1)
df_about_respondents = df_about_respondents.drop('AIEthics', axis=1)
df_about_respondents = df_about_respondents.drop('AIChallenges', axis=1)

In [75]:
df_about_respondents = df_about_respondents.drop('NEWSOSites', axis=1)
df_about_respondents = df_about_respondents.drop('AISelect', axis=1)
df_about_respondents = df_about_respondents.drop('TBranch', axis=1)

In [76]:
df_about_respondents.ICorPM.unique()

array([nan, 'Individual contributor', 'People manager'], dtype=object)

In [77]:
df_about_respondents.ICorPM.value_counts()

ICorPM
Individual contributor    25888
People manager             3913
Name: count, dtype: int64

In [78]:
ICorPM_Mapping = {
    None: 'no answer'
}

df_about_respondents['ICorPM'] = df_about_respondents['ICorPM'].replace(ICorPM_Mapping)
print(df_about_respondents['ICorPM'].unique())

['no answer' 'Individual contributor' 'People manager']


In [79]:

df_about_respondents.WorkExp.unique()

array([nan, 17., 15., 12., 29., 10., 18., 16.,  6.,  7., 14.,  3.,  4.,
        8.,  1.,  9., 27., 31., 35., 25.,  5., 28., 26., 13., 30., 37.,
        2., 24., 20., 23., 19., 21., 11., 34., 32., 22.,  0., 33., 44.,
       40., 41., 36., 45., 39., 50., 38., 48., 42., 46., 43., 49., 47.])

In [80]:
df_about_respondents.WorkExp.value_counts()

WorkExp
3.0     2144
5.0     2050
10.0    2029
2.0     1885
4.0     1767
6.0     1600
7.0     1581
8.0     1554
1.0     1461
15.0    1250
12.0    1249
20.0    1074
9.0      982
11.0     823
25.0     794
13.0     740
14.0     655
16.0     600
17.0     596
18.0     587
30.0     461
24.0     382
19.0     330
22.0     323
23.0     269
26.0     254
21.0     251
27.0     217
35.0     217
28.0     210
0.0      192
40.0     139
29.0     117
32.0     101
33.0      90
36.0      89
34.0      84
31.0      83
37.0      60
38.0      55
50.0      53
42.0      47
45.0      46
39.0      37
41.0      36
43.0      34
44.0      32
46.0      12
48.0       7
47.0       5
49.0       4
Name: count, dtype: int64

In [81]:
df_about_respondents = df_about_respondents.drop('Knowledge_1', axis=1)
df_about_respondents = df_about_respondents.drop('Knowledge_2', axis=1)
df_about_respondents = df_about_respondents.drop('Knowledge_3', axis=1)
df_about_respondents = df_about_respondents.drop('Knowledge_4', axis=1)
df_about_respondents = df_about_respondents.drop('Knowledge_5', axis=1)
df_about_respondents = df_about_respondents.drop('Knowledge_6', axis=1)
df_about_respondents = df_about_respondents.drop('Knowledge_7', axis=1)
df_about_respondents = df_about_respondents.drop('Knowledge_8', axis=1)
df_about_respondents = df_about_respondents.drop('Knowledge_9', axis=1)


In [82]:
df_about_respondents = df_about_respondents.drop('Frequency_1', axis=1)
df_about_respondents = df_about_respondents.drop('Frequency_2', axis=1)
df_about_respondents = df_about_respondents.drop('Frequency_3', axis=1)

In [83]:
df_about_respondents.TimeSearching.unique()

array([nan, '30-60 minutes a day', '60-120 minutes a day',
       '15-30 minutes a day', 'Less than 15 minutes a day',
       'Over 120 minutes a day'], dtype=object)

In [84]:
TimeSearching_Mapping = {
    'Less than 15 minutes a day':'<15 min/day',
    '15-30 minutes a day':'15-30 min/day',
    '30-60 minutes a day':'30-60 min/day',
    '60-120 minutes a day':'60-120 min/day',
    'Over 120 minutes a day':'>120 min/day',   
    None: 'no answer'
}

df_about_respondents['TimeSearching'] = df_about_respondents['TimeSearching'].replace(TimeSearching_Mapping)
print(df_about_respondents['TimeSearching'].unique())

['no answer' '30-60 min/day' '60-120 min/day' '15-30 min/day'
 '<15 min/day' '>120 min/day']


In [85]:
df_about_respondents.TimeAnswering.unique()

array([nan, '60-120 minutes a day', '15-30 minutes a day',
       '30-60 minutes a day', 'Less than 15 minutes a day',
       'Over 120 minutes a day'], dtype=object)

In [86]:
TimeAnswering_Mapping = {
    'Less than 15 minutes a day':'<15 min/day',
    '15-30 minutes a day':'15-30 min/day',
    '30-60 minutes a day':'30-60 min/day',
    '60-120 minutes a day':'60-120 min/day',
    'Over 120 minutes a day':'>120 min/day',   
    None: 'no answer'
}

df_about_respondents['TimeAnswering'] = df_about_respondents['TimeAnswering'].replace(TimeAnswering_Mapping)
print(df_about_respondents['TimeAnswering'].unique())

['no answer' '60-120 min/day' '15-30 min/day' '30-60 min/day'
 '<15 min/day' '>120 min/day']


In [87]:
df_about_respondents.Frustration.unique()

array([nan,
       'Amount of technical debt;Number of software tools in use;Tracking my work;Showing my contributions',
       'Amount of technical debt;Complexity of tech stack for deployment',
       'Amount of technical debt;Complexity of tech stack for deployment;Complexity of tech stack for build;Maintaining security of code being produced',
       'Amount of technical debt;Tracking my work;Complexity of tech stack for build;Patching/updating core components;Maintaining security of systems/platforms used in work;Reliability of tools/systems used in work',
       'Number of software tools in use;Tracking my work;Showing my contributions;Complexity of tech stack for build',
       'Amount of technical debt',
       'Amount of technical debt;Number of software tools in use',
       'None of these',
       'Amount of technical debt;Tracking my work;Showing my contributions;Complexity of tech stack for deployment',
       'Amount of technical debt;Complexity of tech stack for build',


In [88]:
df_about_respondents, Frustration_Counts = process_complex_column(df_about_respondents, 'Frustration')
print(Frustration_Counts)

Frustration
Amount of technical debt                                  17614
Complexity of tech stack for build                         9284
Complexity of tech stack for deployment                    9132
Reliability of tools/systems used in work                  8904
Tracking my work                                           7652
Patching/updating core components                          7091
Number of software tools in use                            6432
Showing my contributions                                   5546
Maintaining security of code being produced                5253
Maintaining security of systems/platforms used in work     4351
None of these                                              2450
Name: count, dtype: int64


In [89]:
df_about_respondents = df_about_respondents.drop('ProfessionalTech', axis=1)
df_about_respondents = df_about_respondents.drop('ProfessionalCloud', axis=1)
df_about_respondents = df_about_respondents.drop('ProfessionalQuestion', axis=1)

In [90]:
df_about_respondents.Industry.unique()

array([nan, 'Healthcare', 'Software Development',
       'Banking/Financial Services', 'Other:',
       'Media & Advertising Services', 'Insurance',
       'Internet, Telecomm or Information Services', 'Higher Education',
       'Energy', 'Fintech', 'Retail and Consumer Services',
       'Manufacturing', 'Government',
       'Computer Systems Design and Services',
       'Transportation, or Supply Chain'], dtype=object)

In [91]:
Industry_Mapping = {
    'Other:': 'Other',
    'Media & Advertising Services': 'Media/Advertising Services',
    'Internet, Telecomm or Information Services': 'Internet/Telecomm/Information Services',
    'Retail and Consumer Services': 'Retail/Consumer Services',
    'Transportation, or Supply Chain': 'Transportation or Supply Chain',
    None: 'no answer'
}

df_about_respondents['Industry'] = df_about_respondents['Industry'].replace(Industry_Mapping)
print(df_about_respondents['Industry'].unique())

['no answer' 'Healthcare' 'Software Development'
 'Banking/Financial Services' 'Other' 'Media/Advertising Services'
 'Insurance' 'Internet/Telecomm/Information Services' 'Higher Education'
 'Energy' 'Fintech' 'Retail/Consumer Services' 'Manufacturing'
 'Government' 'Computer Systems Design and Services'
 'Transportation or Supply Chain']


In [92]:
df_about_respondents.JobSatPoints_1.unique()

array([   nan,   0.  ,  50.  ,  10.  ,  90.  ,  30.  ,  20.  ,   5.  ,
         7.  ,  40.  ,  15.  ,  80.  ,  25.  ,  70.  ,  75.  ,  60.  ,
        33.  ,  35.  ,  22.  , 100.  ,  17.  ,   9.  ,   6.  ,   4.  ,
        34.  ,  45.  ,   8.  ,   1.  ,   3.  ,  14.  ,  29.  ,  67.  ,
         2.  ,  18.  ,  95.  ,  11.  ,  13.  ,  55.  ,  65.  ,  19.  ,
        39.  ,  12.5 ,  12.  ,  85.  ,  32.  ,  89.  ,  16.  ,  99.  ,
        71.  ,  27.  ,  57.  ,  77.  ,  26.  ,  88.  ,  78.  ,  76.  ,
        87.  ,  37.  ,  98.  ,  23.  ,  61.  ,   2.5 ,  86.  ,  24.  ,
        56.  ,  74.  ,  69.  ,  96.  ,  13.5 ,  81.  ,  44.  ,  79.  ,
        18.75,  66.  ,  21.  ,  28.  ,  38.  ,  52.  ,  49.  ,   3.75,
        68.  ,  91.  ,  37.5 ,  31.  ,   8.5 ,  63.  ,  47.  ,  97.  ,
        83.  ,  43.  ,   7.5 ,  36.  ])

In [93]:
df_about_respondents.JobSatPoints_4.unique()

array([   nan,   0.  , 100.  ,  10.  ,  30.  ,  20.  ,   1.  ,  70.  ,
         5.  ,  15.  ,  35.  ,  90.  ,  40.  ,  60.  ,   8.  ,   3.  ,
        25.  ,  80.  ,  50.  ,  75.  ,  14.  ,   9.  ,   2.  ,  12.  ,
         7.  ,  11.  ,  87.  ,   4.  ,  12.5 ,   6.  ,  17.  ,  55.  ,
        45.  ,  89.  ,  99.  ,  33.  ,  67.  ,  13.  ,  85.  ,  66.  ,
        22.  ,  95.  ,  16.  ,  18.  ,  32.  ,  49.  ,  65.  ,  24.  ,
        92.  ,  19.  ,  63.  ,  23.  ,  94.  ,  76.  ,  79.  ,  44.  ,
        56.  ,  77.  ,  27.  ,  69.  ,  34.  ,  26.  ,  86.  ,  98.  ,
         3.75,  51.  ,  52.  ,   9.5 ,  88.  ,  28.  ,  21.  ,  68.  ,
         2.5 ])

In [94]:
df_about_respondents.JobSatPoints_5.unique()

array([    nan,   0.   ,  30.   ,  10.   , 100.   ,   5.   ,  20.   ,
         7.   ,  75.   ,  15.   ,  90.   ,  60.   ,  99.   ,  70.   ,
        50.   ,   3.   ,  16.   ,  25.   ,  12.   ,   9.   ,   4.   ,
        57.   ,  80.   ,   8.   ,   1.   ,   2.   ,  65.   ,  19.   ,
        74.   ,  40.   ,  11.   ,   6.   ,  35.   ,   3.125,  14.   ,
        85.   ,  18.   ,  95.   ,  89.   ,  12.5  ,  21.   ,  13.   ,
        33.   ,  66.   ,  98.   ,  32.   ,  55.   ,  22.   ,  56.   ,
        73.   ,  39.   ,  78.   ,  63.   ,  96.   ,  34.   ,  86.   ,
        45.   ,  77.   ,  69.   ,   7.5  ,  44.   ,  23.   ,  68.   ,
        88.   ,  67.   ,   3.75 ,   8.5  ,  76.   ,  64.   ,  97.   ,
        91.   ,  17.   ,  87.   ,  26.   ,   9.5  ,  27.   ,  24.   ,
        36.   ,  84.   ])

In [95]:
df_about_respondents.JobSatPoints_6.unique()

array([   nan,   0.  ,  25.  ,  30.  ,  60.  , 100.  ,  20.  ,  50.  ,
        15.  ,  10.  ,   5.  ,  80.  ,   8.  ,  65.  ,  90.  ,  75.  ,
        35.  ,  40.  ,  33.  ,  70.  ,  17.  ,   7.  ,  12.  ,  13.  ,
         9.  ,  21.  ,  18.  ,  95.  ,   2.  ,  45.  ,  34.  ,  16.  ,
        78.  ,  85.  ,   1.  ,  14.  ,  31.  ,  11.  ,  23.  ,  28.  ,
        81.  ,   6.25,   6.  ,  55.  ,   3.  ,  22.  ,  42.  ,   4.  ,
        89.  ,  99.  ,  12.5 ,  36.  ,  27.  ,  24.  ,  19.  ,  87.  ,
        88.  ,  29.  ,  33.33,  33.3 ,  37.  ,  39.  ,  77.  ,  68.  ,
        26.  ,  98.  ,  32.  ,  66.  ,  57.  ,  82.  ,  94.  ,  61.  ,
        43.  ,  69.  ,  76.  ,  73.  ,  17.5 ,  46.  ,  49.  ,  52.  ,
        97.  ,  96.  ,  67.  ,  91.  ,  86.  ,  56.  ,  41.  ,  74.  ,
        51.  ,  48.  ,  44.  ,  64.  ,  54.  ,  63.  ])

In [96]:
df_about_respondents.JobSatPoints_7.unique()

array([    nan,   0.   ,  10.   ,  90.   ,  20.   ,  50.   ,  15.   ,
         5.   ,  60.   ,  30.   , 100.   ,   7.   ,  25.   ,  70.   ,
        65.   ,  80.   ,  33.   ,  40.   ,  35.   ,  27.   ,  23.   ,
        14.   ,  12.   ,   9.   ,   8.   ,  18.   ,  37.   ,  75.   ,
         1.   ,  11.   ,  29.   ,  17.   ,   4.   ,  21.   ,  54.   ,
        13.   ,  26.   ,  45.   ,  19.   ,   6.   ,  99.   ,   3.125,
         3.   ,  16.   ,  22.   ,  12.5  ,  85.   ,  24.   ,  55.   ,
        89.   ,  98.   ,  34.   ,  95.   ,  28.   ,   2.   ,  88.   ,
        56.   ,  32.   ,  68.   ,  77.   ,  33.33 ,  33.3  ,  39.   ,
        61.   ,  92.   ,  78.   ,  44.   ,  94.   ,  73.   ,  97.   ,
        87.   ,  81.   ,  31.   ,  18.75 ,  91.   ,  93.   ,  49.   ,
        96.   ,  83.   ,  18.5  ,  69.   ,  48.   ,  46.   ,  82.   ,
        42.   ,  51.   ,  72.   ,  86.   ,  38.   ,  67.   ,  17.5  ,
        36.   ])

In [97]:
df_about_respondents.JobSatPoints_8.unique()

array([   nan,   0.  ,  10.  ,  90.  ,  15.  ,  30.  ,  20.  ,  35.  ,
         5.  ,  70.  ,   7.  , 100.  ,  50.  ,  25.  ,  24.  ,  60.  ,
        40.  ,  80.  ,   9.  ,  45.  ,  16.  ,  27.  ,  55.  ,   3.  ,
         2.  ,   4.  ,  14.  ,  13.  ,  38.  ,   8.  ,  33.  ,  17.  ,
        68.  ,   6.  ,  75.  ,  18.  ,  85.  ,  12.  ,  21.  ,  92.  ,
        37.  ,   1.  ,  95.  ,  32.  ,  65.  ,  43.  ,  99.  ,  89.  ,
        34.  ,  12.5 ,  26.  ,  39.  ,  19.  ,  23.  ,  11.  ,  58.  ,
        88.  ,  98.  ,  28.  ,  66.  ,  57.  ,  22.  ,  33.33,  42.  ,
        69.  ,  53.  ,  67.  ,   7.5 ,  94.  ,  29.  ,  31.  ,  79.  ,
        83.  ,  84.  ,  62.  ,  93.  ,  77.  ,  44.  ,  33.3 ,  97.  ,
        87.  ,  78.  ,  76.  ,  67.5 ,  59.  ,  49.  ,  36.  ,  47.  ,
        56.  ,  86.  ])

In [98]:
df_about_respondents.JobSatPoints_9.unique()

array([   nan,   0.  ,  15.  ,  20.  , 100.  ,  60.  ,   5.  ,  30.  ,
        10.  ,  50.  ,  25.  ,   2.  ,  90.  ,  95.  ,   6.  ,  85.  ,
        35.  ,   4.  ,  12.  ,   9.  ,  40.  ,  70.  ,   8.  ,  75.  ,
        80.  ,   7.  ,  65.  ,   1.  ,   3.  ,  89.  ,  17.  ,  19.  ,
        23.  ,  68.  ,  92.  ,  24.  ,  14.  ,  55.  ,  45.  ,  88.  ,
         1.5 ,  18.  ,  12.5 ,  37.  ,  33.  ,  13.  ,  11.  ,  99.  ,
        44.  ,  34.  ,  16.  ,  26.  ,  21.  ,  32.  ,  67.  ,  33.3 ,
        29.  ,  77.  ,  31.  ,  59.  ,   2.5 ,  28.  ,  22.  ,  76.  ,
         6.5 ,  66.  ,  79.  ,   6.25,  81.  ,  98.  ,  69.  ,  42.  ,
        93.  ,  71.  ,  56.  ,   3.75,  91.  ,  82.  ,  97.  ,   9.5 ,
        14.5 ,  87.  ,  58.  ,  27.  ,  86.  ,  53.  ])

In [99]:
df_about_respondents.JobSatPoints_10.unique()

array([   nan,   0.  ,  10.  ,  90.  ,  40.  ,   5.  ,  60.  ,  50.  ,
        30.  ,  70.  ,  20.  , 100.  ,  80.  ,  75.  ,   2.  ,   7.  ,
        23.  ,   9.  ,  15.  ,  25.  ,   3.  ,   8.  ,   1.  ,  63.  ,
        35.  ,  11.  ,   6.  ,  14.  ,  95.  ,  99.  ,  65.  ,  13.  ,
        85.  ,  19.  ,   4.  ,  89.  ,  55.  ,  12.5 ,  12.  ,  84.  ,
        21.  ,  18.  ,  22.  ,  45.  ,  92.  ,  33.  ,  24.  ,  69.  ,
        96.  ,  77.  ,  88.  ,  78.  ,  16.  ,  17.  ,  87.  ,   1.5 ,
        81.  ,  26.  ,  54.  ,   6.25,  67.  ,  66.  ,  49.  ,  57.  ,
        32.  ,  79.  ,  94.  ,  82.  ,  98.  ,  14.5 ,  93.  ,  43.  ,
        74.  ,  97.  ,  28.  ,  34.  ])

In [100]:
df_about_respondents.JobSatPoints_11.unique()

array([  nan,   0. ,  10. , 100. ,  25. ,   5. ,   3. ,  90. ,   1. ,
        80. ,  50. ,   8. ,  30. ,  15. ,  20. ,  60. ,   6. ,  70. ,
        40. ,  26. ,  11. ,   9. ,  14. ,   7. ,   2. ,  75. ,  66. ,
        65. ,  35. ,   4. ,  85. ,  12. ,  45. ,  18. ,  89. ,  16. ,
        19. ,  99. ,  88. ,  12.5,  21. ,  77. ,  95. ,  96. ,  22. ,
        13. ,  55. ,  36. ,  86. ,  94. ,  17. ,   7.5,  84. ,  98. ,
        24. ,  69. ,  67. ,  28. ,  42. ,  87. ,  31. ,  78. ,  34. ,
        54. ,  44. ,  68. ,  64. ,  97. ,  76. ,  37.5,  37. ,  79. ,
        32. ,  71. ,  53. ,  29. ,  33. ,  59. ,  49. ,  73. ])

In [101]:
df_about_respondents.JobSat.unique()

array([nan,  8.,  5., 10.,  6.,  9.,  4.,  7.,  3.,  2.,  1.,  0.])

In [102]:
df_about_respondents = df_about_respondents.drop('SurveyLength', axis=1)
df_about_respondents = df_about_respondents.drop('SurveyEase', axis=1)

In [103]:
df_about_respondents.ConvertedCompYearly.unique()

array([    nan,   7322.,  30074., ...,  15637.,   9711., 116844.])

In [104]:
# Missing values

# Define the critical columns
critical_columns = ['YearsCode', 'YearsCodePro', 'CompTotal','JobSat', 'WorkExp','ConvertedCompYearly',
                    'JobSatPoints_1', 'JobSatPoints_4','JobSatPoints_5','JobSatPoints_6','JobSatPoints_7',
                    'JobSatPoints_8','JobSatPoints_9','JobSatPoints_10','JobSatPoints_11',]

# Check the percentage of missing values in critical columns
missing_percentage = df_about_respondents[critical_columns].isnull().mean() * 100
print("Percentage of missing values in critical columns:")
print(missing_percentage)

Percentage of missing values in critical columns:
YearsCode               8.508948
YearsCodePro           21.130247
CompTotal              48.438957
JobSat                 55.490013
WorkExp                54.677018
ConvertedCompYearly    64.186928
JobSatPoints_1         55.187432
JobSatPoints_4         55.081987
JobSatPoints_5         55.054480
JobSatPoints_6         54.994881
JobSatPoints_7         54.997937
JobSatPoints_8         54.985711
JobSatPoints_9         54.985711
JobSatPoints_10        54.994881
JobSatPoints_11        55.002522
dtype: float64


In [105]:
# Handling missing values

for column in critical_columns:    
    df_about_respondents[column] = df_about_respondents[column].fillna(0)

In [106]:
# Define experience ranges for YearsCodePro
def categorize_experience(years):
    try:
        years = float(years)
        if years <= 5:
            return '0-5'
        elif years <= 10:
            return '5-10'
        elif years <= 20:
            return '10-20'
        else:
            return '>20'
    except ValueError:
        return None

df_about_respondents['ExperienceRange'] = df_about_respondents['YearsCodePro'].apply(categorize_experience)
df_about_respondents['ExperienceRange'].unique()

array(['0-5', '10-20', '>20', '5-10'], dtype=object)

In [107]:
df_about_respondents.shape

(65437, 255)

In [108]:
df_about_respondents.to_csv('survey-data.csv')


: 